In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification

In [3]:
from sklearn.datasets import make_classification
X,y = make_classification(
    n_features = 10,
    n_samples = 1000,
    n_informative = 4,
    n_repeated = 0,
    n_classes = 2,
    weights=[0.9,0.1],
    random_state = 42)

In [6]:
from collections import Counter
Counter(y)

Counter({0: 895, 1: 105})

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

## using cross fold

In [12]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5,shuffle=True,random_state=42)

In [16]:
for train_index,test_index in kf.split(X,y):
    X_train ,X_test = X[train_index],X[test_index]
    y_train,y_test = y[train_index],y[test_index]
    print(Counter(y_test))
    

Counter({0: 176, 1: 24})
Counter({0: 181, 1: 19})
Counter({0: 180, 1: 20})
Counter({0: 173, 1: 27})
Counter({0: 185, 1: 15})


### we can see there is a imbalnce in the distribution of the folds

## using Stratifed k fold

In [18]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=5,shuffle=True,random_state=42)

In [19]:
for train_index,test_index in skf.split(X,y):
    X_train ,X_test = X[train_index],X[test_index]
    y_train,y_test = y[train_index],y[test_index]
    print(Counter(y_test))

Counter({0: 179, 1: 21})
Counter({0: 179, 1: 21})
Counter({0: 179, 1: 21})
Counter({0: 179, 1: 21})
Counter({0: 179, 1: 21})


### we can see there is a balnce in the distribution of the folds


In [20]:
from sklearn.model_selection import cross_val_score

In [22]:
##logistic
from sklearn.linear_model import LogisticRegression
cross_val_score(LogisticRegression(),X,y,cv=skf)

array([0.89 , 0.9  , 0.9  , 0.905, 0.905])

In [24]:
##decison tree
from sklearn.tree import DecisionTreeClassifier
cross_val_score(DecisionTreeClassifier(criterion='gini'),X,y,cv=skf)

array([0.915, 0.895, 0.93 , 0.94 , 0.925])

In [25]:
from sklearn.tree import DecisionTreeClassifier
cross_val_score(DecisionTreeClassifier(criterion='entropy'),X,y,cv=skf)

array([0.96 , 0.885, 0.945, 0.905, 0.95 ])

In [26]:
##random forest
from sklearn.ensemble import RandomForestClassifier
cross_val_score(RandomForestClassifier(),X,y,cv=skf)

array([0.96 , 0.95 , 0.97 , 0.945, 0.95 ])